type LevelGuide = {
  plain: string;
  how: string;
  /** Lättare ingång om du inte klarar nivån än – det här tar dig från noll. */
  regression?: string;
  /** Den enda tekniknyckel som avgör om repet är rätt. */
  cue?: string;
  /** Tydligt kvitto på att du är redo att gå vidare till nästa nivå. */
  ready?: string;
};

export const LEVEL_GUIDES: Record<string, LevelGuide> = {
  "hand:1": {
    plain: "Aktiv planka på armbågar",
    how: "Ställ dig på armbågarna och tårna. Pressa upp ryggen mellan skulderbladen, sug in naveln och spänn rumpan.",
    regression: "Sviktar axlarna? Kör på knä först och addera tid varje pass tills du klarar full planka.",
    cue: "Tryck övre ryggen mot taket och sug in naveln – det är protraktion, inte att hänga passivt i axlarna.",
    ready: "45s stabil med rund övre rygg och spänd bål → börja gå upp i mage-mot-vägg.",
  },
  "hand:2": {
    plain: "Handstående med magen mot väggen",
    how: "Gå upp med fötterna på väggen tills bröstet nästan är mot väggen. Spänn rumpa och mage, tryck golvet bort från dig.",
    regression: "Börja långt från väggen med bara höften upp (nedåtgående hund) och 'gå' fötterna högre uppför väggen några cm för varje pass. Du behöver inte nå toppen idag.",
    cue: "Tryck golvet ifrån dig så axlarna höjs mot öronen – passiva, hopsjunkna axlar är det vanligaste felet.",
    ready: "30s med bröstet nära väggen och lugn andning → du är redo för rygg-mot-vägg.",
  },
  "hand:3": {
    plain: "Handstående med ryggen mot väggen",
    how: "Kicka upp kontrollerat, låt hälarna nudda väggen och håll kroppen så rak som möjligt.",
    regression: "Vågar du inte sparka upp än? Stanna på mage-mot-vägg och lägg på 5s i taget tills du litar på axlarna.",
    cue: "Kläm rumpa och mage så bananformen försvinner – sikta blicken i golvet mellan händerna.",
    ready: "60s rak och stilla → börja nudda bort hälarna från väggen mot fristående.",
  },
  "hand:4": {
    plain: "Fristående handstående",
    how: "Kicka upp utan vägg och hitta balans med fingrarna. Målet är en lugn hållning, inte att rädda varje sekund.",
    regression: "Kicka upp mot vägg och fånga balansen 1–2s innan hälarna nuddar – samla många korta försök, inte få långa.",
    cue: "Balansera med fingertopparna: tippar du framåt, tryck i fingrarna; tippar du bakåt, släpp trycket.",
    ready: "10s lugnt och samlat → börja flytta händerna i små steg.",
  },
  "hand:5": {
    plain: "Fristående handstående med små steg",
    how: "Håll balansen och flytta händerna korta kontrollerade steg utan att tappa linjen.",
    regression: "Klarar du inte gå än? Håll bara balansen längre och gör mikrojusteringar med fingrarna.",
    cue: "Flytta en hand i taget i korta steg – håll linjen, jaga inte balansen genom att svanka.",
    ready: "30s håll eller kontrollerade småsteg → bygg pressstyrka med pike push-ups.",
  },
  "hand:6": {
    plain: "Pike push-ups",
    how: "Ställ dig i ett uppochnervänt V med händerna och fötterna på golvet. Sänk huvudet kontrollerat framför händerna och pressa upp.",
    regression: "För tungt? Höj händerna på två böcker eller minska höftvinkeln tills du orkar full rörelse.",
    cue: "Sänk hjässan framför händerna i en triangel – armbågarna pekar snett bakåt, inte rakt ut åt sidan.",
    ready: "3×10 med hjässan i golvet → höj fötterna (elevated) för mer vikt på axlarna.",
  },
  "hand:7": {
    plain: "Elevated pike push-ups",
    how: "Som vanliga pike push-ups men placera fötterna upphöjt på en bänk eller stol för att lägga mer vikt på axlarna.",
    regression: "Sänk fothöjden (lägre pall) tills 8 reps känns rena, höj sen.",
    cue: "Ju mer lodrät överkropp desto mer axelarbete – håll höften hög och ryggen lång.",
    ready: "3×8 djupa reps → börja med handstativ-armhävning mot vägg.",
  },
  "hand:8": {
    plain: "Handstående armhävningar mot vägg",
    how: "Stå mot väggen, sänk huvudet kontrollerat mot golvet och pressa upp igen.",
    regression: "Börja med halva djupet eller pulsa bara de översta centimetrarna och öka rörelsen efter hand.",
    cue: "Sänk hjässan i en triangel framför händerna (inte rakt ner) och pressa hela vägen till låsta armbågar.",
    ready: "4×5 med hjässan i golvet → testa fristående HSPU.",
  },
  "hand:9": {
    plain: "Fristående handstående armhävning",
    how: "Samma press som mot vägg, men utan stöd. En ren repetition räcker för nivån.",
    regression: "Träna fristående håll + HSPU mot vägg parallellt tills styrkan och balansen möts.",
    cue: "Pressa explosivt ur botten men håll linjen – balansen tappas oftast på vägen upp.",
    ready: "1 ren rep från balans → börja flytta vikt mot en arm.",
  },
  "hand:10": {
    plain: "Assisterat enarmshandstående",
    how: "Stå vid vägg och flytta mer vikt till ena handen medan den andra bara hjälper lätt.",
    regression: "Flytta bara 60–70% av vikten till en hand först och öka andelen gradvis.",
    cue: "Stapla axeln rakt över handen och tryck golvet ifrån dig – flytta tyngdpunkten, luta inte kroppen.",
    ready: "10s med större delen av vikten på en hand → mot fri enarm.",
  },
  "hand:11": {
    plain: "Enarmshandstående",
    how: "Håll kroppen stabil på en hand med kontroll i fingrar, axel och höft.",
    regression: "Fortsätt med assisterad enarm och minska stödet centimeter för centimeter.",
    cue: "Allt sker i fingrar, axel och höft – mikrojustera konstant, något statiskt finns inte här.",
    ready: "Elitmålet – fira varje sekund du står på en hand.",
  },

  "drag:1": {
    plain: "Aktivt häng i stången",
    how: "Häng med raka armar i stången. Dra ner skuldrorna bort från öronen och spänn bålen för att undvika att gunga.",
    regression: "Tappar du greppet snabbt? Dela upp i 3×15s, eller ställ fötterna lätt på en pall/band så du kan avlasta och bygga upp tiden.",
    cue: "Dra ner skuldrorna bort från öronen – passivt häng ('hänga i senorna') ska bli aktivt häng ('hänga i musklerna').",
    ready: "30s aktivt häng utan att gunga → börja med negativa pull-ups.",
  },
  "drag:2": {
    plain: "Bygg dragstyrka med sänkningar eller rows",
    how: "Hoppa upp till toppen av en pull-up och sänk långsamt, eller gör australiska rows om pull-ups är för tunga.",
    regression: "Är negativan för tung? Gör australiska rows med fötterna i marken och höj sen svårigheten.",
    cue: "Sänk så långsamt du kan med skuldrorna nere – kontrollen i botten bygger pull-upen.",
    ready: "Sänkning på 5s under full kontroll → testa strikta pull-ups.",
  },
  "drag:3": {
    plain: "Strikta pull-ups",
    how: "Starta från raka armar, dra hakan över stången och sänk kontrollerat utan gung.",
    regression: "Klarar du inte 8? Kör negativa (hoppa upp, sänk på 5s) och australiska rows under en stång tills grundstyrkan finns.",
    cue: "Starta varje rep från HELT raka armar och dra hakan över stången – halva reps räknas inte.",
    ready: "4×8 strikta och rena → börja lägga på extravikt eller gå mot archer pull-ups.",
  },
  "drag:4": {
    plain: "Pull-ups med extra vikt",
    how: "Lägg på lätt vikt och håll samma rena teknik som vanliga pull-ups.",
    regression: "Börja med 2,5–5 kg och behåll formen; öka när alla reps är rena.",
    cue: "Samma strikta start från raka armar – låt inte vikten dra in dig i gung.",
    ready: "4×5 med +10 kg rent → börja med archer för enarmsöverföring.",
  },
  "drag:5": {
    plain: "Archer pull-ups",
    how: "Dra dig mer mot ena handen medan den andra armen hjälper mindre. Växla sida.",
    regression: "Låt hjälparmen vara mer böjd och ta mer last först; räta ut den gradvis.",
    cue: "Dra dig mot den arbetande handen – hjälparmen sträcks ut åt sidan som en utriggare.",
    ready: "4×4/sida med nästan rak hjälparm → börja med enarms-negativ.",
  },
  "drag:6": {
    plain: "Enarms-sänkning",
    how: "Starta högt med en hand och sänk så långsamt du kan utan att tappa skulderkontroll.",
    regression: "Förkorta sänkningen (toppen → halvvägs) och förläng tiden efter hand.",
    cue: "Håll skuldran nere och aktiv hela vägen – tappar du den smäller armbågen rakt.",
    ready: "5s kontrollerad sänkning på en arm → assisterad enarms-pull-up.",
  },
  "drag:7": {
    plain: "Assisterad enarmspull-up",
    how: "Dra med en huvudhand och använd andra handen lätt på handduk, band eller fingerstöd.",
    regression: "Använd mer hjälp (handduk/band högre upp) och minska den gradvis.",
    cue: "Huvudarmen gör jobbet, andra handen ger bara en knuff – fuska inte över till tvåarmsdrag.",
    ready: "3×3 med minimal hjälp → den rena one-arm pull-upen är nära.",
  },
  "drag:8": {
    plain: "One-arm pull-up",
    how: "En strikt repetition med en arm från häng till haka över handen.",
    regression: "Fortsätt med assisterad enarm och krymp stödet tills det inte längre behövs.",
    cue: "Explosiv start med låst skuldra – ingen kipp, ingen sving.",
    ready: "Elitmålet – en ren rep räknas för livet.",
  },

  "front:1": {
    plain: "Scapula-pulls i stången",
    how: "Häng med raka armar och dra dig uppåt enbart genom att sänka och dra ihop skulderbladen. Håll armarna helt raka.",
    regression: "Ingen stång? Gör scapula-pushups på golvet för samma skulderkontroll.",
    cue: "Armarna helt raka – rörelsen kommer bara från att dra ner skulderbladen, inte från armbågen.",
    ready: "3×10 rena med raka armar → vidare till skin the cat.",
  },
  "front:2": {
    plain: "Skin the cat",
    how: "Häng i stången, dra knäna genom armarna och rotera höften bakåt så långt axelmobiliteten tillåter, vänd sedan kontrollerat tillbaka.",
    regression: "Gå bara så långt bak axlarna tillåter, böj knäna och öka rörelseomfånget varje gång.",
    cue: "Rör dig långsamt och håll greppet hårt – det här bygger axelmobilitet säkert.",
    ready: "3×3 med full kontrollerad rotation → tuck front lever.",
  },
  "front:3": {
    plain: "Tuck front lever",
    how: "Häng i stången, lås armarna, dra ner skuldrorna och håll knäna nära bröstet med ryggen nästan horisontell.",
    regression: "För tungt? Höj höften något (mindre horisontell) eller kör skin the cat först för att vänja axlarna vid läget.",
    cue: "Raka armar, dra skuldrorna ner/bak och dra stången mot höften – det är en rakarmsdragning, inte en bålböj.",
    ready: "4×10s med ryggen vågrät och knäna mot bröstet → öppna höften mot advanced tuck.",
  },
  "front:4": {
    plain: "Advanced tuck front lever",
    how: "Som tuck, men öppna höften mer så knäna kommer längre från bröstet.",
    regression: "Dra in knäna lite mer (mot tuck) tills du klarar tiden, öppna sen gradvis.",
    cue: "Håll ryggen vågrät och platt – en rak linje från axel till svank, inte en kutryggad boll.",
    ready: "4×8s med öppnad höft → sträck ut ett ben.",
  },
  "front:5": {
    plain: "Front lever med ett ben ut",
    how: "Håll ena benet rakt och andra böjt. Växla sida mellan set.",
    regression: "Sträck benet bara halvvägs först, eller väx mellan tuck och utsträckt inom setet.",
    cue: "Pressa det raka benets häl bort från dig och håll höften i nivå – luta inte åt sidan.",
    ready: "4×6s per sida → straddle front lever.",
  },
  "front:6": {
    plain: "Straddle front lever",
    how: "Båda benen raka och brett isär för att göra full lever lättare.",
    regression: "Smalna av benen (mindre straddle) tills du klarar tiden, bredda sen.",
    cue: "Bredd isär benen sänker hävarmen – håll båda benen raka och höften öppen.",
    ready: "4×5s stabilt → för ihop benen mot full front lever.",
  },
  "front:7": {
    plain: "Full front lever",
    how: "Båda benen raka ihop, kroppen horisontell, armar raka och skuldror aktiva.",
    regression: "Pendla mellan straddle och full inom setet tills full-hållet växer.",
    cue: "Hela kroppen en vågrät planka – raka armar, aktiva skuldror, spänd rumpa.",
    ready: "Elitmålet – 5s ren full lever är en milstolpe.",
  },

  "planche:1": {
    plain: "Armhävningar på knä",
    how: "Ställ dig på knä och händer. Sänk bröstet kontrollerat mot golvet och pressa upp. Håll kroppen rak från knä till axel.",
    regression: "För tungt? Gör armhävningar mot vägg eller bänk (högre = lättare) och sänk höjden efter hand.",
    cue: "Rak linje från knä till axel – höften får inte sticka upp; bröstet leder rörelsen ner.",
    ready: "3×10 djupa och raka → börja med planche-lutning.",
  },
  "planche:2": {
    plain: "Planche-lutning",
    how: "Stå i armhävningsposition och luta axlarna framför händerna med raka armar.",
    regression: "Klarar du inte 20s? Stå på knä i lutningen, eller minska lutningen så axlarna bara är någon cm framför händerna och bygg därifrån.",
    cue: "Raka armbågar (vrid armvecken framåt) och skjut bröstet långt förbi händerna – det är lutningen, inte armböjen, som bygger planchen.",
    ready: "4×20s med tydlig framåtlutning och låsta armar → testa frog stand och tuck planche.",
  },
  "planche:3": {
    plain: "Frog stand",
    how: "Placera händerna på golvet, sätt knäna mot armbågarna och luta dig framåt tills fötterna lämnar marken.",
    regression: "Sätt knäna högt upp mot armhålan, böj armbågarna som en hylla och luta långsamt tills bara EN tå lättar. Lägg en kudde framför pannan så fallrädslan försvinner.",
    cue: "Blicken framåt (inte ner i golvet) – det flyttar tyngdpunkten över händerna så fötterna lättar av sig själva.",
    ready: "30s stadig balans → du har viktfördelningen som krävs för tuck planche med raka armar.",
  },
  "planche:4": {
    plain: "Tuck planche",
    how: "Händer i golvet, knän indragna, fötterna lyfter från marken och armarna är raka (knäna vilar inte på armbågarna).",
    regression: "Utgå från frog stand: räta gradvis ut armarna och lyft knäna bort från armbågarna någon sekund i taget.",
    cue: "Helt raka armar, skjut skuldrorna framåt och runda övre ryggen (protraktion) – annars bär du på axeln i stället för musklerna.",
    ready: "10s med raka armar och knäna fritt i luften → öppna höften mot advanced tuck.",
  },
  "planche:5": {
    plain: "Advanced tuck planche",
    how: "Som tuck planche och mer öppen höft med knäna längre bak.",
    regression: "Dra in knäna mot tuck tills du klarar tiden; öppna höften gradvis.",
    cue: "Skuldrorna långt fram förbi händerna och raka armar – lutningen ÄR planchen.",
    ready: "4×8s med öppen höft → sträck ut till straddle.",
  },
  "planche:6": {
    plain: "Straddle planche",
    how: "Armar raka, kropp svävande och benen raka brett isär.",
    regression: "Smalare ben och mer framåtlutning först; bredda benen efter hand.",
    cue: "Bredda benen för kortare hävarm – pressa golvet bort och håll höften i axelhöjd.",
    ready: "3×5s stabilt → för ihop benen mot full planche.",
  },
  "planche:7": {
    plain: "Full planche",
    how: "Hela kroppen rak och horisontell med bara händerna i marken.",
    regression: "Väx mellan straddle och full inom setet tills full-hållet sitter.",
    cue: "Hela kroppen en vågrät linje, raka armar, skuldror maximalt protraherade.",
    ready: "3×3s ren full planche → planche push-ups.",
  },
  "planche:8": {
    plain: "Planche push-ups",
    how: "Håll planche-position och gör små kontrollerade pressar utan att tappa formen.",
    regression: "Gör små pulsar i toppen av straddle planche och öka djupet efter hand.",
    cue: "Behåll planche-linjen genom hela repet – tappa inte höften när du sänker.",
    ready: "Elitmålet – press i full balans, toppen av push-styrkan.",
  },

  "flag:1": {
    plain: "Sidoplanka på armbåge",
    how: "Ligg på sidan med stöd på armbågen. Lyft höften så att kroppen bildar en rak linje. Håll positionen statiskt.",
    regression: "För tungt? Böj knäna och stötta på nedre knät i stället för fötterna – kortare hävarm gör hållet lättare.",
    cue: "Pressa nedre axeln bort från golvet och stapla höften rakt ovanför – låt den inte sjunka, det är där sekunderna tappas.",
    ready: "45s per sida stabilt → börja greppa en stolpe och känn på flaggstödet.",
  },
  "flag:2": {
    plain: "Flaggstöd (tryck/drag-kontroll)",
    how: "Greppa en stolpe med fötterna på marken. Ena armen trycker och den andra drar. Lär dig spänna bålen i denna position.",
    regression: "Håll fötterna i marken och lätta bara vikten gradvis – känn in tryck/drag innan du lyfter något ben.",
    cue: "Nedre armen TRYCKER ifrån, övre armen DRAR in – som att försöka bryta stolpen mitt itu.",
    ready: "Stabil 30s med tryck/drag-känslan → dra upp mot vertikal chamber-flagga.",
  },
  "flag:3": {
    plain: "Vertikal flaggposition",
    how: "Greppa en stolpe, tryck med nedre armen och dra med övre. Börja med kroppen mer lodrätt än horisontell.",
    regression: "Håll kroppen mer lodrät (närmare lodrätt läge) och sänk vinkeln gradvis mot horisontellt.",
    cue: "Nedre armen trycker, övre drar – kläm ihop hela bålsidan för att hålla höften uppe.",
    ready: "5×10s stabilt → dra ut benen till tuck-flagga.",
  },
  "flag:4": {
    plain: "Tuck-flagga",
    how: "Lyft kroppen från stolpen med knäna indragna. Målet är sidolyft, inte att klättra.",
    regression: "Dra in knäna hårt mot bröstet för kortast hävarm; öppna sen gradvis.",
    cue: "Lyft kroppen sidledes ut från stolpen – det är ett lyft med bålsidan, inte en klättring.",
    ready: "5×8s med knäna inne → sträck ut ett ben.",
  },
  "flag:5": {
    plain: "Flagga med ett ben ut",
    how: "Håll tuck-flaggan men sträck ut ett ben för att öka hävarmen.",
    regression: "Sträck benet halvvägs eller väx mellan tuck och utsträckt inom setet.",
    cue: "Sträck översta benet och håll höften staplad – sjunk inte ihop i midjan.",
    ready: "4×6s per sida → straddle-flagga.",
  },
  "flag:6": {
    plain: "Straddle-flagga",
    how: "Båda benen raka och brett isär medan kroppen hålls sidledes från stolpen.",
    regression: "Smalna av benen tills du klarar tiden, bredda sen.",
    cue: "Bredd isär benen sänker hävarmen – håll kroppen i en rak sidolinje.",
    ready: "4×5s → för ihop benen mot full flagga.",
  },
  "flag:7": {
    plain: "Full mänsklig flagga",
    how: "Kroppen rak och horisontell från stolpen med båda benen ihop.",
    regression: "Väx mellan straddle och full inom setet tills full-hållet växer.",
    cue: "Rak vågrät kropp – tryck/drag i armarna och stenhård bål håller linjen.",
    ready: "Elitmålet – människoflaggan är en av de häftigaste skills som finns.",
  },

  "core:1": {
    plain: "Liggande knälyft (böjda knän)",
    how: "Ligg på rygg med ländryggen pressad mot golvet. Dra upp knäna mot bröstet och sänk kontrollerat utan att ländryggen lämnar golvet.",
    regression: "Lägg händerna under svanken för stöd om ländryggen lyfter, och minska rörelsen.",
    cue: "Pressa ländryggen i golvet hela tiden – tappar svanken kontakten är det höftböjaren, inte bålen, som jobbar.",
    ready: "3×10 med svanken kvar i golvet → hollow hold.",
  },
  "core:2": {
    plain: "Hollow hold",
    how: "Ligg på rygg, pressa ländryggen i golvet och håll armar och ben lyfta.",
    regression: "Tappar ländryggen kontakten? Dra in knäna (tuck hollow) eller håll armarna längs sidorna i stället för över huvudet – sänk hävarmen tills du klarar tiden.",
    cue: "Pressa ländryggen HÅRT i golvet hela tiden – glipar svanken har du tappat övningen, oavsett hur länge du ligger kvar.",
    ready: "40s med svanken kvar i golvet → nästa steg är hängande knälyft (kräver stång).",
  },
  "core:3": {
    plain: "Hängande knälyft",
    how: "Häng från stång och lyft knäna kontrollerat utan att gunga.",
    regression: "Ingen stång hemma? Bygg vidare på hollow hold + liggande raka benlyft tills du har tillgång till en stång.",
    cue: "Lyft med bålen, inte med svingen – pausa en tiondels sekund i toppen så momentum inte gör jobbet.",
    ready: "3×12 rena utan gung → räta benen mot hängande raka benlyft.",
  },
  "core:4": {
    plain: "Hängande raka benlyft",
    how: "Häng från stång och lyft raka ben upp mot höfthöjd eller högre.",
    regression: "Böj knäna något (halvraka ben) och räta ut dem efter hand.",
    cue: "Lyft med bålen och tippa bäckenet – inte med svingen. Pausa i toppen.",
    ready: "3×8 raka ben till höfthöjd → L-sit och dragon flag-progression.",
  },
  "core:5": {
    plain: "L-sit på händer / paralletter",
    how: "Håll dig uppe med raka armar på marken eller paralletter och lyft benen rakt framåt i 90 grader.",
    regression: "Börja med tuck L-sit: tryck upp på två böcker eller låga pallar och håll knäna indragna 5s. Sänk höjden när det börjar kännas lätt, räta sen benen ett i taget.",
    cue: "Tryck skuldrorna NER (deppa inte ihop), raka armar – och spänn framsida lår för att få upp benen i 90°.",
    ready: "10s med raka ben i 90° → grunden för all hängande bålstyrka och dragon flag är på plats.",
  },
  "core:6": {
    plain: "Negativ dragon flag",
    how: "Starta högt på rygg med kroppen rak och sänk långsamt utan att svanka.",
    regression: "Sänk med böjda knän (tuck) först och räta benen gradvis.",
    cue: "Håll kroppen spikrak från axel till tå och sänk långsamt – svanka inte, det är där ryggen tar över.",
    ready: "5×5s kontrollerad rak sänkning → tuck dragon flag.",
  },
  "core:7": {
    plain: "Tuck dragon flag",
    how: "Gör dragon flag med knäna indragna för kortare hävarm.",
    regression: "Dra in knäna mer för kortare hävarm; öppna gradvis.",
    cue: "Endast skulderbladen i kontakt med underlaget – resten av kroppen är en stel planka.",
    ready: "4×8 kontrollerade → räta ut mot full dragon flag.",
  },
  "core:8": {
    plain: "Full dragon flag",
    how: "Kroppen hålls rak från axlar till fötter medan du lyfter och sänker kontrollerat.",
    regression: "Väx mellan tuck och full inom setet tills full-reps sitter.",
    cue: "Spänn rumpa och bål stenhårt – hela kroppen rör sig som en planka kring axlarna.",
    ready: "Elitmålet – Bruce Lees signaturövning.",
  },

  "mu:1": {
    plain: "Vanliga strikta pull-ups",
    how: "Dra dig upp från helt raka armar till hakan över stången. Håll kroppen stilla utan gung.",
    regression: "Klarar du inte 3? Kör negativa + australiska rows tills de första rena reps kommer.",
    cue: "Full rörelse: raka armar i botten, haka över stången i toppen.",
    ready: "3 rena reps → bygg vidare mot 8 strikta.",
  },
  "mu:2": {
    plain: "Strikta pull-ups (styrka)",
    how: "Gör pull-ups med strikt kontroll och sänkning. Målet är att öka grundstyrkan.",
    regression: "Bygg volym med set på 4–5 reps och addera reps varje vecka.",
    cue: "Strikt och stilla – ingen kipp, för muscle-upen byggs på ren dragstyrka.",
    ready: "8 strikta → börja göra dem explosiva.",
  },
  "mu:3": {
    plain: "Explosiva pull-ups till bröstet",
    how: "Dra högre än vanligt och sikta på att få stången mot bröstet.",
    regression: "Sikta först på halsen/nyckelbenet och höj måttet gradvis mot bröstet.",
    cue: "Dra så snabbt och högt du kan – kraften i starten avgör hur högt du når.",
    ready: "Stången når bröstet → sikta ännu högre (mot midjan).",
  },
  "mu:4": {
    plain: "Höga pull-ups mot midjan",
    how: "Dra explosivt så långt upp och ut att stången närmar sig midjan.",
    regression: "Nå först nedre revbenen och jobba dig längre ner mot midjan.",
    cue: "Dra explosivt och luta dig lätt bakåt i toppen – bana väg för övergången över stången.",
    ready: "Stången mot nedre bröst/midja → testa negativ muscle-up.",
  },
  "mu:5": {
    plain: "Negativ muscle-up",
    how: "Starta ovanför stången och sänk långsamt genom övergången ner till häng.",
    regression: "Hoppa upp till stödet och sänk bara genom övergången, först snabbt sen långsammare.",
    cue: "Luta överkroppen fram över stången i övergången – det är där rörelsen vinns.",
    ready: "Kontrollerad sänkning genom övergången → muscle-up med band.",
  },
  "mu:6": {
    plain: "Muscle-up med band",
    how: "Använd band för hjälp genom övergången, men håll rörelsen strikt.",
    regression: "Tjockare band (mer hjälp) och minska tjockleken gradvis.",
    cue: "Explosiv start + kom tidigt fram över stången – låt inte bandet göra hela jobbet.",
    ready: "4×3 med tunt band → en strikt muscle-up är inom räckhåll.",
  },
  "mu:7": {
    plain: "Strikt bar muscle-up",
    how: "Dra högt, rotera över stången och pressa ut utan kipp.",
    regression: "Fortsätt med band + höga pull-ups tills övergången går utan hjälp.",
    cue: "Dra högt, kasta bröstet fram över stången och pressa ut – allt utan kipp.",
    ready: "Elitmålet – 1 ren strikt muscle-up.",
  },

  "rings:1": {
    plain: "Support-hållning assisterad",
    how: "Håll i ringarna med raka armar men låt fötterna vila lätt mot marken för att avlasta vikten och stabilisera ringarna.",
    regression: "Sänk fötterna mer i marken för mer avlastning och lyft dem gradvis.",
    cue: "Lås armbågarna, dra skuldrorna ner och kläm ringarna mot kroppen för att stoppa skakningen.",
    ready: "30s stabil med lätt fotstöd → vanliga dips på barr.",
  },
  "rings:2": {
    plain: "Dips på barren",
    how: "Kör vanliga dips på stänger för att bygga upp press- och axelstyrkan som krävs för ringdips.",
    regression: "Använd band eller halvdjup först; öka djup och reps efter hand.",
    cue: "Håll axlarna nere och kroppen lätt framåtlutad – sänk till 90° i armbågen.",
    ready: "3×8 djupa dips → support-hållning på ringar.",
  },
  "rings:3": {
    plain: "Support hold på ringar",
    how: "Håll dig uppe med raka armar, ringarna nära kroppen och axlarna nere.",
    regression: "Börja med fötterna lätt i marken eller kortare set och bygg upp.",
    cue: "Lås armbågarna, tryck ringarna ner och in – stabiliteten kommer från att 'krama' ringarna.",
    ready: "30s stilla utan skak → ring dips.",
  },
  "rings:4": {
    plain: "Ring dips",
    how: "Sänk kontrollerat i ringarna och pressa upp utan att ringarna flyger ut.",
    regression: "Banddips i ringar eller stötta lätt med fötterna; minska hjälpen gradvis.",
    cue: "Håll ringarna nära kroppen hela vägen – flyger de ut tappar du kontrollen.",
    ready: "4×8 stabila → börja vrida ut till RTO support.",
  },
  "rings:5": {
    plain: "RTO support",
    how: "Håll support-position med ringarna lätt utåtroterade så armvecken pekar framåt.",
    regression: "Vrid bara ut ringarna en bit (halv-RTO) och öka rotationen efter hand.",
    cue: "Vrid handflatorna framåt så armvecken pekar fram – aktiv utåtrotation hela tiden.",
    ready: "20s full RTO → negativ ring fly.",
  },
  "rings:6": {
    plain: "Negativ ring fly",
    how: "Från stöd, öppna armarna långsamt utåt med kontroll och kom tillbaka säkert.",
    regression: "Öppna armarna bara en bit och kortare sänkning; öka omfånget försiktigt för armbågarnas skull.",
    cue: "Raka armar, öppna långsamt ut åt sidorna och håll skuldrorna nere – skona armbågsleden.",
    ready: "5×5s kontrollerad öppning → iron cross med band.",
  },
  "rings:7": {
    plain: "Iron cross med band",
    how: "Använd bandhjälp och håll armarna ut åt sidorna med kroppen stabil.",
    regression: "Tjockare band och kortare håll; minska hjälpen gradvis.",
    cue: "Tryck armarna NER mot höften, inte ut – iron cross hålls med lats, inte axlar.",
    ready: "3×5s med tunt band → fri iron cross.",
  },
  "rings:8": {
    plain: "Iron cross",
    how: "Håll kroppen i ringarna med armarna rakt ut åt sidorna.",
    regression: "Fortsätt med band och negativ fly tills hållet bär utan hjälp.",
    cue: "Armarna rakt ut, tryck ner i ringarna och lås hela kroppen – ren järnstyrka.",
    ready: "Elitmålet – en av styrkans absolut tuffaste hållningar.",
  },
};

export function levelGuide(trackId: string, idx: number) {
  return LEVEL_GUIDES[`${trackId}:${idx}`];
}
